tagFormat: "${version}"
repositoryUrl: git@github.com:chaseconey/auth0-proxy.git
branches:
  - main
plugins:
  - "@semantic-release/changelog"
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@semantic-release/git"
