---

version: '3'
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      DB_HOST: mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_DATABASE=laravel
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
